//
// Created by Noverish Harold on 2018. 5. 25..
//

#ifndef CPU_SCHEDULING_SIMULATOR_OPTIONS_H
#define CPU_SCHEDULING_SIMULATOR_OPTIONS_H

#define PROCESS_NUM 10

#define P_ID_NUM_START 1000
#define P_ID_NUM_END 9999

#define CPU_BURST_START_NUM 1
#define CPU_BURST_END_NUM 20

#define IO_BURST_START_NUM 0
#define IO_BURST_END_NUM 10

#define ARRIVAL_START_NUM 0
#define ARRIVAL_END_NUM 10

#define PRIORITY_START_NUM 0
#define PRIORITY_END_NUM 10

#define READY_QUEUE_SIZE 100
#define WAITING_QUEUE_SIZE 100

#endif //CPU_SCHEDULING_SIMULATOR_OPTIONS_H
